-- Lote 6 de noticias (50 notícias: 251 a 300)
INSERT INTO public.noticias (
  id, titulo, slug, resumo, conteudo, imagem_url,
  categoria_id, autor_id, data_publicacao, views, destaque, meta_title, meta_description
) VALUES
  ('30874ed2-7ffa-45d6-b8a3-513cf48d83c4', 'Carlinhos Sobral lidera avaliações na disputa pela Assembleia Legislativa da Bahia', 'carlinhos-sobral-lidera-avaliacoes-na-disputa-pela-assembleia-legislativa-da', 'Pesquisa do Foco na Bahia aponta Carlinhos Sobral como o candidato mais bem avaliado para a Assembleia Legislativa da Bahia.', 'Uma pesquisa de opinião divulgada pelo portal Foco na Bahia indica que Carlinhos Sobral ocupa a primeira colocação entre os nomes mais bem avaliados no cenário eleitoral para a Assembleia Legislativa da Bahia (Alba). O levantamento destaca a preferência do eleitorado baiano em relação aos principais candidatos que concorrem ao cargo de deputado estadual nas próximas eleições.

O estudo analisou a percepção da população sobre a capacidade de gestão e o perfil dos postulantes, apontando Carlinhos Sobral como o candidato com maior aceitação e reconhecimento no estado. Os dados refletem a dinâmica política local e o interesse da sociedade em acompanhar as trajetórias dos políticos que buscam representação no legislativo estadual. A divulgação dos resultados serve como referência para a análise do atual momento eleitoral na Bahia.', 'https://api.proradiobr.com/imagens-publicas/carlinhos-sobral-lidera-avaliacoes-na-disputa-pela-assembleia-legislativa-da.webp', '91925efe-8c0d-42a7-8e21-1d167b8f670b', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-15 20:58:41.494311+00', 1013, true, 'Carlinhos Sobral lidera pesquisa para a Assembleia da Bahia', 'Levantamento do portal Foco na Bahia mostra que Carlinhos Sobral é o nome mais bem avaliado na disputa pelas vagas da Assembleia Legislativa da Bahia.'),
  ('5e707c20-c018-4a64-bb8b-184a5e886c21', 'Idoso é atropelado por viatura da Polícia Civil que trafegava na contramão em Ibotirama', 'idoso-e-atropelado-por-viatura-da-policia-civil-que-trafegava-na-contramao-em', 'Idoso de 65 anos foi atropelado por viatura da Polícia Civil em Ibotirama, BA. A corporação afirma que o condutor trafegava na contramão e o caso está sob investigação pericial.', 'Um idoso de 65 anos, identificado preliminarmente como Cícero, ficou ferido após ser atropelado por uma viatura da Polícia Civil enquanto pilotava uma motocicleta na tarde desta segunda-feira, 14, no Centro de Ibotirama, no oeste da Bahia. Conforme informações obtidas pela reportagem, a viatura teria atingido a motocicleta enquanto trafegava na contramão, circunstância que ainda será esclarecida pela investigação conduzida pela própria corporação.

Segundo o A TARDE, os policiais retornavam de um atendimento e seguiam para uma diligência com horário marcado no Fórum local. Durante o deslocamento, a equipe encontrou um congestionamento causado por carretas na rodovia. Diante do atraso, o condutor da viatura acionou a sirene para agilizar a passagem. Após a colisão, foi registrado boletim de ocorrência e a Polícia Técnica foi acionada para periciar os veículos. A vítima foi socorridida pelo Samu e levada a uma unidade médica, sem informações atualizadas sobre seu estado de saúde. A Delegacia Territorial de Ibotirama apura o caso, com oitivas e exames periciais em andamento para definir a dinâmica do acidente.', 'https://api.proradiobr.com/imagens-publicas/idoso-e-atropelado-por-viatura-da-policia-civil-que-trafegava-na-contramao-em.webp', '91925efe-8c0d-42a7-8e21-1d167b8f670b', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-16 11:37:34.268507+00', 1007, true, 'Idoso atropelado por viatura da PC na contramão em Ibotirama', 'Idoso foi atropelado por viatura da Polícia Civil em Ibotirama. A corporação afirma que o condutor trafegava na contramão e o caso está sob investigação.'),
  ('5872441b-11e5-4d65-9af8-f7e667597635', 'Greve na Caixa: Saiba como sacar PIS e FGTS durante a paralisação', 'greve-na-caixa-saiba-como-sacar-pis-e-fgts-durante-a-paralisacao', 'A Caixa Econômica Federal está em greve nacional após rejeição de proposta. O atendimento presencial foi impactado, mas o acesso a benefícios como PIS e FGTS segue disponível por canais digitais, caixas eletrônicos, lotéricas e Correspondentes Caixa Aqui.', 'A Caixa Econômica Federal iniciou na última quinta-feira, 10, uma greve nacional por tempo indeterminado. A paralisação ocorreu após os empregados da instituição financeira rejeitarem a proposta para renovar o Acordo Coletivo de Trabalho, com 90% dos votos válidos. A entidade sindical apontou que a proposta estava distante das reivindicações da categoria, especialmente em relação ao Saúde Caixa, o plano de saúde dos funcionários do banco. A greve impacta o atendimento presencial das agências e pode afetar o acesso a benefícios sociais como FGTS, INSS e Bolsa Família, já que o banco gerencia 30 tipos de benefícios e atende cerca de 56 milhões de pessoas.

Apesar da paralisação, os pagamentos de benefícios não foram suspensos e o acesso aos valores não foi interrompido, pois os canais remotos da Caixa continuam disponíveis para movimentação e verificação. O impacto se manifesta quando o beneficiário necessita de atendimento presencial para acessar ou regularizar algum pagamento, como para emitir, desbloquear ou alterar a senha do Cartão do Cidadão, que pode exigir suporte especializado em casos não resolvidos em lotéricas ou caixas eletrônicos. Durante a greve, os clientes podem utilizar o aplicativo Caixa, Internet Banking, WhatsApp da Caixa (0800 104 0104), Caixa Tem e Cartões Caixa. Além disso, caixas eletrônicos, rede Banco24Horas, unidades lotéricas e Correspondentes Caixa Aqui permanecem operacionais. O aplicativo Caixa Tem permite transferências via Pix, pagamento de contas e saque sem cartão nos caixas eletrônicos, enquanto os Correspondentes Caixa Aqui oferecem saques simples e consultas.', 'https://api.proradiobr.com/imagens-publicas/greve-na-caixa-saiba-como-sacar-pis-e-fgts-durante-a-paralisacao.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-16 11:37:35.334922+00', 1008, true, 'Greve da Caixa: Canais para sacar PIS, FGTS e benefícios', 'A Caixa Econômica Federal está em greve nacional. Descubra os canais alternativos disponíveis para sacar seu PIS, FGTS e outros benefícios, evitando o atendimento presencial afetado.'),
  ('02da2f77-c9e8-4dad-a6c1-e7e3ab29183b', 'Bahia oferece até 95% de desconto para regularizar dívida ativa até 18 de dezembro', 'bahia-oferece-ate-95-de-desconto-para-regularizar-divida-ativa-ate-18-de', 'Sefaz e PGE-BA oferecem desconto de até 95% em multas e acréscimos para regularização de dívida ativa até 18 de dezembro, com parcelamento em até seis vezes.', 'Contribuintes com díbitos tributários inscritos em dívida ativa na Bahia têm até 18 de dezembro para regularizar suas pendências fiscais com o Estado. A medida, lançada pela Secretaria da Fazenda (Sefaz) e pela Procuradoria Geral do Estado (PGE-BA), prevê descontos de até 95% sobre multas e acréscimos moratórios, além da possibilidade de parcelamento em até seis vezes.

A iniciativa beneficia pessoas físicas e jurídicas cujos Processos Administrativos Fiscais (PAFs) tenham gerado créditos inscritos em dívida ativa até 31 de dezembro de 2025, desde que cumpridos os requisitos do edital. A adesão está disponível a partir desta quinta-feira (15), pelos sites da Sefaz e da PGE.

A regularização pode ter reflexos na esfera criminal, uma vez que o não recolhimento de tributos pode configurar crime contra a ordem tributária. No caso do ICMS, especialmente quando o imposto é declarado e não recolhido de forma reiterada e deliberada, a conduta pode enquadrar-se no crime previsto no artigo 2º, inciso II, da Lei nº 8.137/1990, característica do chamado devedor contumaz.', 'https://api.proradiobr.com/imagens-publicas/bahia-oferece-ate-95-de-desconto-para-regularizar-divida-ativa-ate-18-de.webp', '91925efe-8c0d-42a7-8e21-1d167b8f670b', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-16 11:46:14.559563+00', 1006, true, 'Bahia oferece até 95% de desconto em dívida ativa até 18 de dezembro', 'Contribuintes da Bahia podem regularizar dívida ativa com desconto de até 95% em multas e parcelamento em até 6 vezes até 18 de dezembro.'),
  ('9f705bd0-1372-4f7a-9e65-f9e49049f6fe', 'Incêndio de grandes proporções atinge pastagem em Ribeira do Pombal', 'incendio-de-grandes-proporcoes-atinge-pastagem-em-ribeira-do-pombal', 'Um incêndio de grandes proporções atingiu pastagens em Ribeira do Pombal nesta quarta-feira (16), causando preocupação. Moradores acionaram o Corpo de Bombeiros. Este é o segundo incidente na semana na região, que enfrenta período de seca.', 'Um incêndio de grandes proporções foi registrado nesta quarta-feira (16) na região da Manteiga, entre as localidades de Manteiga e Boa Hora, em Ribeira do Pombal. As chamas, que se espalharam rapidamente, atingiram extensas áreas de pastagem, gerando preocupação entre os moradores e proprietários de imóveis rurais da área afetada. Diante da dimensão do fogo e do risco de avanço das chamas para outras propriedades, a população local acionou o Corpo de Bombeiros. As equipes estão sendo aguardadas para iniciar o combate. Até o momento, não foram confirmadas as causas do incêndio, nem há informações sobre possíveis danos materiais ou pessoais.

Este episódio ocorre em um período de altas temperaturas, baixa umidade relativa do ar e vegetação seca, condições climáticas que favorecem significativamente a rápida propagação de incêndios, especialmente em áreas de pastagem e vegetação nativa. A preocupação da comunidade é ampliada por outro incêndio ocorrido na terça-feira (15), que também atingiu uma área de pastagem na região do Bangolá. Diante desse cenário, as autoridades recomendam que a população redobre os cuidados e evite qualquer prática que possa deflagrar focos de incêndio, principalmente o uso de fogo próximo a áreas com vegetação seca. Em caso de avistamento de chamas, a orientação é acionar imediatamente o Corpo de Bombeiros e não tentar combater o fogo sem os equipamentos de segurança adequados. A situação está sendo acompanhada pela Bahia Gazeta.', 'https://imagemlink.cleissoncardoso.com/uploads/71719774-213c-4136-a091-ede48d4282d8.png', '7d34292b-4217-4571-ba21-f7aa996aa1d3', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-16 15:09:53.962551+00', 1040, true, 'Incêndio de grandes proporções atinge pastagem em Ribeira do Pombal', 'Ribeira do Pombal registrou um grande incêndio em área de pastagem nesta quarta-feira. Moradores acionaram os Bombeiros. É o segundo caso em dois dias, em período de seca e altas temperaturas. Causas e danos são apurados.'),
  ('3bba77af-781e-47c6-8b9f-9aed3a8b205a', 'Cliente busca R$ 3 e R$ 1 mil por danos morais na Justiça de Cabo de Santo Agostinho, mas processo é encerrado', 'cliente-busca-r-3-e-r-1-mil-por-danos-morais-na-justica-de-cabo-de-santo', 'Uma cliente buscou na Justiça de Cabo de Santo Agostinho a devolução de R$ 3 e indenização de R$ 1 mil por danos morais. O processo foi encerrado sem análise do mérito, pois o juiz considerou que a petição não demonstrou interesse processual nem lesão efetiva.', 'Uma ação judicial buscando a restituição de um pagamento de R$ 3 via Pix e uma indenização de R$ 1 mil por danos morais foi encerrada sem análise do mérito pelo Juizado Especial Cível de Cabo de Santo Agostinho, em Pernambuco. A autora da ação relatou ter realizado a transferência em 29 de agosto de 2026 para a aquisição de um produto ou serviço que não teria sido entregue. Ela também afirmou ter enfrentado transtornos e perdido tempo ao tentar resolver a questão com a empresa de soluções financeiras acionada no processo.

Ao examinar o caso, o juiz Patrick de Melo Gariolli concluiu pela ausência de interesse processual. O magistrado argumentou que a petição não demonstrou consequências concretas da perda dos R$ 3, nem um fato independente que sustentasse o pedido de danos morais. Gariolli ressaltou que o baixo valor não é o critério principal para o encerramento, mas sim a verificação de uma lesão efetiva e a utilidade da intervenção judicial. Classificando a situação como uma “demanda de bagatela”, o juiz destacou a desproporção entre o benefício econômico pretendido e os recursos públicos mobilizados. A decisão também levou em conta que a autora não teria recorrido a alternativas extrajudiciais, como Procons ou plataformas de consumidor, antes de ajuizar a ação, que foi apresentada poucos dias após o pagamento. Apesar de extinguir a ação, o juiz afastou a existência de má-fé, não impondo multas ou condenação ao pagamento de custas processuais.', 'https://api.proradiobr.com/imagens-publicas/cliente-busca-r-3-e-r-1-mil-por-danos-morais-na-justica-de-cabo-de-santo.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-16 16:16:03.646744+00', 1017, true, 'Justiça de Cabo de Santo Agostinho encerra processo por R$ 3 e danos morais', 'Cliente acionou a Justiça em Cabo de Santo Agostinho, PE, para reaver R$ 3 via Pix e pedir R$ 1 mil por danos morais. O juiz encerrou o caso por falta de interesse processual.'),
  ('8338b8d0-0000-4b0d-9625-778608ed90a1', 'ANTT inicia testes com sistema de controle de velocidade média em rodovias federais', 'antt-inicia-testes-com-sistema-de-controle-de-velocidade-media-em-rodovias', 'A ANTT começou a testar um novo sistema de controle de velocidade média em trechos de rodovias federais concedidas. Os projetos-piloto avaliam a tecnologia em condições reais de operação. Nesta fase, não haverá autuações, e a iniciativa tem caráter educativo e experimental.', 'A Agência Nacional de Transportes Terrestres (ANTT) autorizou projetos-piloto para testar o controle de velocidade média em trechos de rodovias federais concedidas. Esta solução será avaliada em condições reais de operação para que a Agência possa verificar a confiabilidade dos dados, o funcionamento dos equipamentos, o comportamento dos usuários e o desempenho da operação. Nesta etapa, não haverá autuação ou penalidade com fundamento exclusivamente na velocidade média registrada no trecho monitorado. As autorizações, emitidas pela Superintendência de Infraestrutura Rodoviária (Surod) em 9 de setembro de 2026, estabelecem experimentos em caráter provisório e experimental. Um dos trechos autorizados é um segmento de três quilômetros da BR-101/SC, sob concessão da ViaCosteira, com previsão de 180 dias de teste.

O sistema de controle de velocidade média se diferencia do modelo tradicional que verifica a velocidade em um único ponto. Ele calcula a velocidade média do veículo entre dois pontos de monitoramento, considerando a distância percorrida e o tempo gasto. A ANTT acompanhará os resultados dos testes antes de avaliar futuras aplicações da solução, com as concessionárias enviando relatórios mensais à Surod. Entre os aspectos analisados estão a confiabilidade dos dados e o comportamento dos usuários. A Agência ressalta que o projeto-piloto é exclusivamente técnico, educativo e experimental, não gerando multas. Qualquer utilização futura para fiscalização sancionatória dependerá de novas avaliações e autorizações.', 'https://api.proradiobr.com/imagens-publicas/antt-inicia-testes-com-sistema-de-controle-de-velocidade-media-em-rodovias.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-16 16:16:57.734549+00', 1004, true, 'ANTT testa sistema de velocidade média em rodovias federais', 'A ANTT autorizou projetos-piloto para testar o controle de velocidade média em rodovias federais concedidas. Entenda a fase experimental sem autuações.'),
  ('92d657a0-04f9-4246-a6d1-e56cd9c62c7f', 'PF investiga fraudes de R$ 80 milhões na Educação de Belo Horizonte e cumpre mandados em 6 estados', 'pf-investiga-fraudes-de-r-80-milhoes-na-educacao-de-belo-horizonte-e-cumpre', 'A Polícia Federal deflagrou a 10ª fase da Operação Overclean para investigar suspeitas de fraudes em contratos da Educação de Belo Horizonte. A ação cumpre 24 mandados em seis estados, apurando indícios de direcionamento em contratos que superam R$ 80 milhões.', 'A Polícia Federal (PF) deflagrou, nesta quinta-feira (17), a 10ª fase da Operação Overclean, que investiga suspeitas de fraudes em contratações da Secretaria Municipal de Educação de Belo Horizonte. A apuração foca em procedimentos realizados entre 2024 e 2025, envolvendo o fornecimento de serviços e materiais didáticos. A operação cumpre 24 mandados de busca e apreensão em seis estados: Minas Gerais, Bahia, São Paulo, Tocantins, Paraná e Espírito Santo, com alvos também no território baiano.

A investigação da PF apura a possível atuação de uma organização criminosa nos processos de contratação. Foram identificados indícios de direcionamento em, ao menos, três contratos que, somados, ultrapassam R$ 80 milhões. Outros processos de contratação da Secretaria Municipal de Educação de Belo Horizonte também estão sob análise. A Polícia Federal não detalhou quais municípios baianos são alvo dos mandados desta fase. Em tese, os fatos apurados podem caracterizar crimes contra a administração pública, fraudes em licitações e contratos, organização criminosa e lavagem de dinheiro.', 'https://api.proradiobr.com/imagens-publicas/pf-investiga-fraudes-de-r-80-milhoes-na-educacao-de-belo-horizonte-e-cumpre.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-17 10:46:06.873111+00', 1007, true, 'PF investiga fraudes de R$ 80 mi na Educação de BH em operação nacional', 'A Polícia Federal lançou a 10ª fase da Operação Overclean para apurar suspeitas de fraudes em contratos de mais de R$ 80 milhões na Secretaria de Educação de Belo Horizonte, com mandados em seis estados.'),
  ('1364e1c2-cc00-4e7b-9522-4e1af6cc511f', 'Fiat Palio colide com reboque e fica com frente destruída em Ribeira do Pombal; condutor teria fugido', 'fiat-palio-colide-com-reboque-e-fica-com-frente-destruida-em-ribeira-do-pombal', 'Um Fiat Palio branco ficou com a frente destruída em Ribeira do Pombal após colidir com um reboque na BR-110. O equipamento se desprendeu de outro veículo, cujo condutor teria deixado o local sem prestar assistência. Não houve feridos no acidente.', 'Um Fiat Palio branco teve a parte frontal parcialmente destruída após uma colisão com um reboque, ocorrida na BR-110, em Ribeira do Pombal. O acidente aconteceu às margens da Orla do Açude, causando danos materiais significativos ao veículo de passeio. Apesar da gravidade do impacto, não houve registro de vítimas feridas, conforme informações apuradas no local.

De acordo com o relato da proprietária do Fiat Palio, o reboque estava acoplado a outro automóvel que seguia à frente do seu carro. Em determinado momento, o equipamento teria se desprendido, atingindo violentamente a frente do Palio. Após a colisão, o condutor do veículo que tracionava o reboque supostamente removeu o equipamento e deixou o local do acidente, sem prestar assistência ou buscar um acordo sobre os prejuízos. As circunstâncias exatas que levaram ao desprendimento do reboque e a identificação do outro veículo envolvido não foram informadas.', 'https://imagemlink.cleissoncardoso.com/uploads/ce44dafc-c448-4468-aa74-9eebec9761ef.png', '7d34292b-4217-4571-ba21-f7aa996aa1d3', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-17 14:24:35.597274+00', 1021, true, 'Palio colide com reboque em Ribeira do Pombal; condutor teria fugido', 'Um Fiat Palio branco teve a frente destruída após colidir com um reboque solto na BR-110, em Ribeira do Pombal. O motorista do veículo que transportava o reboque teria fugido do local sem prestar socorro ou acordo.'),
  ('9137ffec-a9ae-4bba-82a7-3bc43e382174', 'Empresário de Fátima (BA) morre em queda de avião monomotor em Macambira (SE)', 'empresario-de-fatima-ba-morre-em-queda-de-aviao-monomotor-em-macambira-se', 'Um empresário de Fátima (BA) faleceu em um acidente de avião monomotor em Macambira (SE) nesta quinta-feira (17). A SSP/SE corrigiu o número de vítimas para uma morte, e o Seripa II investigará as causas da queda.', 'Uma aeronave monomotor caiu na zona rural do município de Macambira, a 74 km de Aracaju (SE), na manhã desta quinta-feira (17). A Secretaria de Estado da Segurança Pública de Sergipe (SSP/SE) confirmou o acidente, que resultou na morte de uma pessoa. Inicialmente, a secretaria havia reportado duas vítimas fatais, mas corrigiu a informação posteriormente, confirmando apenas um óbito. Equipes de socorro permanecem no local para atender a ocorrência.

A vítima foi identificada como Horácio, popularmente conhecido como Chitão. Ele era empresário e proprietário de uma funerária em Fátima (BA), cidade onde residia. O Serviço Regional de Investigação e Prevenção de Acidentes Aeronáuticos (Seripa II), responsável por apurar ocorrências na Região Nordeste, informou que ainda não foi notificado oficialmente sobre o caso. Contudo, o órgão declarou que enviará uma equipe ao local para iniciar as investigações necessárias e determinar as causas do acidente.', 'https://imagemlink.cleissoncardoso.com/uploads/27a18b11-cfa0-4078-82bc-08daadd0106f.png', 'ebffbf51-6728-401d-9f59-3a334902bdfc', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-17 18:16:12.746462+00', 1023, true, 'Empresário de Fátima (BA) morre em queda de avião em Macambira (SE)', 'Empresário de Fátima (BA), Horácio, faleceu em acidente de avião monomotor em Macambira (SE) nesta quinta-feira (17). Uma vítima confirmada pela SSP/SE.'),
  ('bc061f2b-6106-4bf8-b844-c2cc4a51d52d', 'Cipó se despede do locutor Luiz Henrique Coelho Nogueira', 'cipo-se-despede-do-locutor-luiz-henrique-coelho-nogueira', 'O radialista Luiz Henrique Coelho Nogueira, natural de Minas Gerais e radicado há muitos anos em Cipó, faleceu nesta segunda-feira, 17 de agosto. Ele tinha passagens pela Rádio Milênio FM e, mais recentemente, pelo Canal Cipó. Estava internado havia alguns dias no Hospital Geral Santa Tereza, em decorrência de complicações da diabetes.', '
A comunidade de Cipó recebeu com pesar a notícia do falecimento de Luiz Henrique Coelho Nogueira, conhecido locutor de rádio na região. Ele tinha 66 anos, era natural de Minas Gerais e havia se radicado no município há muitos anos.

Ao longo de sua carreira, Nogueira marcou presença na Rádio Milenium  FM e, mais recentemente, atuava no Canal Cipó, construindo uma relação próxima com ouvintes e telespectadores da região.

Segundo informações da família, o radialista enfrentava complicações relacionadas à diabetes e estava internado havia alguns dias no Hospital Geral Santa Tereza. (Causa oficial da morte não confirmada por boletim médico até o momento — informação baseada em apuração inicial junto a amigos próximos.)

Nogueira deixa esposa e filho. Colegas de trabalho, ouvintes e amigos têm manifestado condolências nas redes sociais, destacando sua contribuição para a comunicação em Cipó. O sepultamento ocorreu ainda hoje, às 17h.', 'https://mkbnqyhvaozqfpmcyoyw.supabase.co/storage/v1/object/public/imagens/noticias/1789681107074_l02k2p0.webp', '3949c67e-3936-409d-9600-28782301730d', NULL, '2026-09-17 21:38:54.728+00', 1511, true, 'Cipó perde locutor Luiz Henrique Nogueira, da Milenium FM e Canal Cipó', 'Falece em Cipó o radialista Luiz Henrique Coelho Nogueira, com passagens pela Milênio FM e Canal Cipó. '),
  ('d0212cbd-c144-4a5a-82c3-6abf083d89e8', 'Polícia Civil apreende armas e drogas em operação em Euclides da Cunha', 'policia-civil-apreende-armas-e-drogas-em-operacao-em-euclides-da-cunha', 'Operação da Polícia Civil em Euclides da Cunha apreende armas e drogas, resultando na prisão em flagrante de um suspeito por tráfico e posse ilegal de arma.', 'A Polícia Civil da Bahia deflagrou na manhã desta quinta-feira (17) a Operação Happy Birthday no município de Euclides da Cunha. A ação foi resultado de uma investigação sobre tráfico de drogas e contou com o cumprimento de sete mandados de busca e apreensão domiciliar expedidos pela Justiça local.

Durante as diligências, os agentes apreenderam dois revólveres, calibres .38 e .32, munições, 83 papelotes de pó branco análogo à cocaína, 70 porções de erva esverdeada análoga à maconha, um papelote de skank, nove porções de haxixe e cerca de 50 gramas de cocaína a granel. Também foram recolhidos três celulares e anotações ligadas ao tráfico.

Um investigado, identificado pelas iniciais J. F. dos S., que usava tornozeleira eletrônica, foi preso em flagrante e autuado por tráfico de drogas e posse ilegal de arma de fogo. Para W. R. M., foi instaurado inquérito pelos mesmos crimes. A operação recebeu o nome de "Happy Birthday" devido a informações sobre a distribuição de entorpecentes durante as comemorações do aniversário da cidade. Participaram equipes da 25ª COORPIN, GATTI Conselheiro, Núcleo de Inteligência e delegacias de Euclides da Cunha, Tucano, Ribeira do Pombal, Nova Soure e Cansanção.', 'https://api.proradiobr.com/imagens-publicas/policia-civil-apreende-armas-e-drogas-em-operacao-em-euclides-da-cunha.webp', '32987db5-45a5-4de9-8212-7e87dbc8f24e', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-18 12:52:37.694792+00', 108, true, 'Operação em Euclides da Cunha apreende armas e drogas', NULL),
  ('3912f0eb-a522-4c32-beb9-c5a6350ed2ac', 'Show de Nattanzinho Lima em Euclides da Cunha é cancelado após avião não conseguir pousar em Lagarto', 'show-de-nattanzinho-lima-em-euclides-da-cunha-e-cancelado-apos-aviao-nao', 'O avião do cantor Nattanzinho Lima não conseguiu pousar em Lagarto devido ao tempo fechado, resultando no cancelamento de seu show em Euclides da Cunha, Bahia. O artista aterrissou em Aracaju, mas a apresentação foi suspensa.', 'O avião que transportava o cantor Nattanzinho Lima não conseguiu pousar na cidade de Lagarto, em Sergipe, nesta terça-feira, devido às condições climáticas adversas. Segundo informações do tráfego aéreo, a aeronave realizou aproximadamente cinco tentativas de aproximação na região do aeródromo do Hospital de Amor, mas o tempo fechado impossibilitou a operação, gerando grande impacto na agenda do artista.

Após as tentativas frustradas em Lagarto, o cantor conseguiu pousar em Aracaju, capital sergipana, conforme ele mesmo divulgou em suas redes sociais. Contudo, apesar do pouso seguro, a apresentação que Nattanzinho Lima faria em Euclides da Cunha, na Bahia, foi oficialmente cancelada devido aos imprevistos gerados pela impossibilidade de pouso no local inicialmente planejado.', 'https://imagemlink.cleissoncardoso.com/uploads/f72e1187-8866-45a8-aa66-aff1b49c4f00.png', '32987db5-45a5-4de9-8212-7e87dbc8f24e', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-18 13:47:39.168634+00', 1022, true, 'Show de Nattanzinho Lima em Euclides da Cunha cancelado por mau tempo em Lagarto', 'Aeronave de Nattanzinho Lima tentou pousar em Lagarto, mas o tempo fechado impediu. O fato resultou no cancelamento do show em Euclides da Cunha, Bahia.'),
  ('e39a2a7b-e251-4801-b8eb-937361774171', 'Polícia prende Uedison "Menga" em Ribeira do Pombal com mandado judicial', 'policia-prende-uedison-menga-em-ribeira-do-pombal-com-mandado-judicial', 'Uedison Cipriano Ferreira, conhecido como "Menga", foi preso em Ribeira do Pombal por mandado judicial. Ele tem diversas passagens pela Justiça por furtos e arrombamentos, e já foi envolvido em outras ocorrências, incluindo um episódio onde foi atingido por um disparo.', 'A Polícia prendeu, na cidade de Ribeira do Pombal, Uedison Cipriano Ferreira, conhecido pelo apelido de "Menga". A prisão ocorreu em cumprimento a um mandado expedido pela Justiça. Conforme informações apuradas, Uedison possui um extenso histórico de passagens pela Justiça, com registros de diversos crimes, incluindo furtos e arrombamentos.

Em ocasiões anteriores, imagens de câmeras de segurança atribuídas a ele, registrando ações criminosas, chegaram a ser divulgadas nas redes sociais. Recentemente, um vídeo também circulou mostrando-o sendo atingido por um disparo de arma de fogo na mão, em uma situação que, segundo relatos, estaria ligada a uma tentativa de furto. Mesmo após esses incidentes, ele teria voltado a se envolver em novas ocorrências. A investigação também levou à prisão de outras duas pessoas, por envolvimento no espancamento sofrido por Uedison.', 'https://imagemlink.cleissoncardoso.com/uploads/6ddf8bbf-b0f2-466c-ae4d-a53fbf77980e.png', '7d34292b-4217-4571-ba21-f7aa996aa1d3', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-18 20:35:39.604819+00', 1047, true, 'Polícia prende "Menga" em Ribeira do Pombal por mandado judicial', 'Uedison "Menga" Ferreira foi preso em Ribeira do Pombal, Bahia, em cumprimento a mandado de prisão. Ele tem histórico de furtos e arrombamentos.'),
  ('f4d78f7f-84ce-4cfe-b328-e04caa77befa', 'Julio Iglesias enfrenta novo pedido de investigação por suposta agressão sexual na Espanha', 'julio-iglesias-enfrenta-novo-pedido-de-investigacao-por-suposta-agressao-sexual', 'Ex-funcionárias pedem investigação na Espanha contra Julio Iglesias por supostos abusos. Cantor nega as acusações e Justiça local deve analisar o caso.', 'Duas ex-funcionárias de Julio Iglesias, de 82 anos, solicitaram à Justiça espanhola a abertura de uma investigação sobre novas denúncias de suposta agressão sexual, assédio e trabalho forçado. Segundo as mulheres, os episódios teriam ocorrido em 2021, durante o período em que trabalhavam em propriedades do cantor localizadas nas Bahamas e na República Dominicana.

A queixa foi protocolada em 3 de setembro, meses após o arquivamento da primeira denúncia por falta de competência da Justiça espanhola para julgar fatos ocorridos no exterior. A organização Women''s Link Worldwide, que representa as denunciantes, argumenta que os tribunais espanhóis podem analisar o caso devido aos vínculos do artista com o país. Em comunicado, as mulheres pedem o reconhecimento de seus direitos à justiça e relatam supostas condições de trabalho degradantes. Julio Iglesias nega as acusações, classificando os relatos como absolutamente falsos e afirmando nunca ter abusado ou coagido qualquer mulher. A Justiça espanhola agora avaliará a nova denúncia para decidir se instaura o procedimento investigativo.', 'https://api.proradiobr.com/imagens-publicas/julio-iglesias-enfrenta-novo-pedido-de-investigacao-por-suposta-agressao-sexual.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-19 11:55:06.00972+00', 1004, true, 'Julio Iglesias alvo de novo pedido de investigação na Espanha', 'Duas ex-funcionárias pedem à Justiça espanhola a investigação de supostos abusos cometidos por Julio Iglesias. O cantor nega as alegações.'),
  ('9ab9f79e-0a38-49f2-a5f8-1bb260fd6b77', 'Governo federal reajusta Bolsa Família em 15% a partir de outubro', 'governo-federal-reajusta-bolsa-familia-em-15-a-partir-de-outubro', 'O governo federal reajustou o Bolsa Família em 15% com base no INPC. O valor mínimo passa a ser de R$ 691 e o médio de R$ 777, valendo a partir de outubro.', 'O benefício do programa social Bolsa Família sofrerá um reajuste de 15%, correspondente à variação inflacionária acumulada pelo Índice Nacional de Preços ao Consumidor (INPC) entre março de 2023 e agosto de 2026. Com a atualização, o valor mínimo do benefício passa a ser de R$ 691, enquanto o valor médio pago às famílias beneficiárias reachará R$ 777. A medida foi oficializada por decreto assinado pelo presidente Luiz Inácio Lula da Silva em 17 de setembro e publicado em edição extra do Diário Oficial da União.

O decreto entra em vigor na data da publicação, mas os efeitos financeiros começam a valer a partir de 1º de outubro. Além do valor mínimo, o texto reajusta outros componentes do benefício: o Benefício de Renda de Cidadania sobe para R$ 164 por integrante da família, o Benefício Primeira Infância para R$ 173 e o Benefício Variável Familiar para R$ 58. Durante a cerimônia no Palácio do Planalto, o secretário-executivo do Ministério do Planejamento, Bruno Moretti, destacou que a correção visa preservar o poder de compra dos beneficiários. O ministro da Fazenda, Dario Durigan, acrescentou que a reposição busca evitar perdas inflacionárias e garantir segurança alimentar às famílias mais vulneráveis, projetando que o custo do programa represente entre 1,2% e 1,25% do PIB em 2027.', 'https://api.proradiobr.com/imagens-publicas/governo-federal-reajusta-bolsa-familia-em-15-a-partir-de-outubro.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-19 11:55:20.626251+00', 1002, true, 'Bolsa Família é reajustado em 15% e vale a partir de outubro', 'Governo federal reajusta Bolsa Família em 15%. Valor mínimo sobe para R$ 691 e médio para R$ 777, com efeitos financeiros a partir de outubro.'),
  ('04e06c78-7323-4fe2-abfc-e6f406ced822', 'Candidatos às eleições 2026 não poderão ser presos a partir de sábado', 'candidatos-as-eleicoes-2026-nao-poderao-ser-presos-a-partir-de-sabado', 'A partir de sábado, candidatos às eleições 2026 não poderão ser presos, salvo em flagrante. A regra do Código Eleitoral vale até 48h após o primeiro turno de 4 de outubro.', 'Candidatas e candidatos que disputam as eleições 2026 estão protegidos por uma garantia jurídica que impede prisões e detenções a partir deste sábado, 19. A medida, prevista no Código Eleitoral, vale pelos 15 dias que antecedem o primeiro turno, marcado para 4 de outubro, e se estende até 48 horas após o encerramento da votação.

Durante o período de vigência dessa proteção, restrições de liberdade só serão permitidas em casos de flagrante delito. A garantia abrange todos os candidatos devidamente registrados para a disputa. Segundo o calendário aprovado pelo Tribunal Superior Eleitoral (TSE), os eleitores irão às urnas em 4 de outubro para escolher presidente da República, governadores, senadores e deputados federais, estaduais e distritais.', 'https://api.proradiobr.com/imagens-publicas/candidatos-as-eleicoes-2026-nao-poderao-ser-presos-a-partir-de-sabado.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-19 11:55:39.249986+00', 1007, true, 'Candidatos 2026 não podem ser presos a partir de sábado', 'Proteção a candidatos vale de 19 de setembro a 48h após as urnas de 4 de outubro. Detenções só em flagrante delito, segundo TSE.'),
  ('64265328-f5a2-44a5-b080-c38c564bd065', 'Lula promete acabar com apostas esportivas caso seja reeleito', 'lula-promete-acabar-com-apostas-esportivas-caso-seja-reeleito', 'Lula prometeu proibir apostas esportivas se for reeleito, citando casos de vício e tentativas de suicídio entre jovens. Ele argumentou que a saúde pública está acima da arrecadação tributária do setor.', 'O presidente Luiz Inácio Lula da Silva defendeu a proibição das casas de apostas esportivas durante um discurso realizado na noite desta sexta-feira, 18, em Guarulhos, na Região Metropolitana de São Paulo. O chefe do Executivo afirmou que pretende encerrar a operação de bets no país caso consiga um novo mandato, citando o impacto negativo do vício na saúde pública e na vida de jovens brasileiros.

Ao justificar a posição, Lula relatou ter conversado com uma jovem que, segundo ele, tentou tirar a própria vida três vezes por causa do vício em apostas. O presidente classificou as bets como a coisa mais horrorosa que viu na vida e associou essas plataformas a problemas financeiros e comportamentos compulsivos, como a ludopatia. Ele ressaltou que a preocupação com a segurança e a saúde dos jovens está acima da arrecadação tributária gerada pelo setor.

Lula também respondeu às críticas de clubes de futebol, como Flamengo e Corinthians, que alertaram para possíveis impactos econômicos da restrição. O presidente argumentou que equipes tradicionais conquistaram títulos mundiais antes da presença das casas de apostas no esporte e reafirmou que não pode permitir que a vida dos jovens seja arruinada em prol de impostos.', 'https://api.proradiobr.com/imagens-publicas/lula-promete-acabar-com-apostas-esportivas-caso-seja-reeleito.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-19 21:12:26.716986+00', 1005, true, 'Lula promete proibir bets se for reeleito', 'Presidente defendeu fim das apostas esportivas em discurso em Guarulhos, citando vício e impacto na saúde de jovens, e ignorou críticas de clubes de futebol.'),
  ('b11a8412-bee3-4ba4-a24b-e97787c2c708', 'Mulher é flagrada tentando levar maconha em ovos para presídio em Patos', 'mulher-e-flagrada-tentando-levar-maconha-em-ovos-para-presidio-em-patos', 'Mulher foi flagrada com 90g de maconha em ovos durante visita a presídio em Patos, PB. Material foi apreendido e será analisado.', 'Uma mulher foi detida pela Polícia Penal na sexta-feira, 18, ao tentar ingressar no Presídio Padrão Regional Romero Nóbrega, localizado no município de Patos, na Paraíba. Durante a revista de rotina, os agentes identificaram sinais de adulteração em ovos alimentícios que a visitante portava. A inspeção minuciosa permitiu a localização de 90 gramas de substância análoga à maconha, oculta no interior dos alimentos.

Após a apreensão do material, as medidas legais cabíveis foram adotadas imediatamente. A Secretaria de Estado da Administração Penitenciária da Paraíba (Seap) informou que a substância será submetida a análise laboratorial para a confirmação definitiva de sua composição química. As autoridades não divulgaram a identidade da mulher detida nem do interno que seria o destinatário do material ilícito. A Polícia Penal do estado ressaltou que o caso integra a série de ocorrências envolvendo o tráfico de entorpecentes por meio de alimentos dentro da instituição.', 'https://api.proradiobr.com/imagens-publicas/mulher-e-flagrada-tentando-levar-maconha-em-ovos-para-presidio-em-patos.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-19 21:12:41.009838+00', 1003, true, 'Mulher leva maconha em ovos para presídio em Patos e é detida', 'Visitante foi detida ao tentar entrar no presídio de Patos com 90g de maconha escondida em ovos. Seap confirmou a apreensão.'),
  ('c7a2b9c0-45e4-4d91-858d-405de4ba86ee', 'Ribeira do Pombal anuncia construção de 300 casas no João do Alto', 'ribeira-do-pombal-anuncia-construcao-de-300-casas-no-joao-do-alto', 'Ribeira do Pombal anunciará a construção de 300 casas no bairro João do Alto durante os 93 anos do município, somando-se às 144 unidades já em fase final de obras.', 'A Prefeitura de Ribeira do Pombal anunciará a construção de 300 novas unidades habitacionais do programa Minha Casa, Minha Vida, todas localizadas no bairro João do Alto. O anúncio ocorrerá durante a programação comemorativa dos 93 anos de emancipação política do município, marcando uma nova etapa no projeto habitacional em andamento na região.

Atualmente, 144 unidades habitacionais já se encontram em fase final de obras, próximas de serem entregues às famílias beneficiadas. Com a adição das 300 novas moradias, o bairro João do Alto ampliará significativamente o número de famílias contempladas, tornando-se o principal polo de expansão habitacional da cidade.

A iniciativa integra a agenda de investimentos apresentada no aniversário da cidade, que inclui projetos em saúde, educação, infraestrutura, pavimentação, esporte, mobilidade e saneamento. Entre os anúncios previstos para 19 de setembro, destaca-se a ordem de serviço para o esgotamento sanitário da sede, além de novas licitações para pavimentação de povoados e intervenções urbanas. Essa expansão visa ampliar o acesso à casa própria e fortalecer a infraestrutura urbana local.', 'https://api.proradiobr.com/imagens-publicas/ribeira-do-pombal-anuncia-construcao-de-300-casas-no-joao-do-alto.webp', '7d34292b-4217-4571-ba21-f7aa996aa1d3', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-19 22:17:25.9513+00', 195, true, 'Ribeira do Pombal anuncia 300 novas casas no João do Alto', NULL),
  ('d1b95ca2-1051-40e9-b84a-e1dd0103f02b', 'Ribeira do Pombal celebra 93 anos com inaugurações e anúncio de investimentos em infraestrutura e saúde', 'ribeira-do-pombal-celebra-93-anos-com-inauguracoes-e-anuncio-de-investimentos', 'O município inaugurou UBS, quadras e escolas, além de anunciar pavimentação de 15 povoados, 300 moradias populares e implantação de esgotamento sanitário na sede.', 'Ribeira do Pombal celebrou neste sábado, 19 de setembro, seus 93 anos de emancipação política com uma agenda oficial marcada por inaugurações, entregas de equipamentos públicos e anúncios de novos investimentos para a sede e comunidades rurais. As comemorações iniciaram com ato ecumênico e hasteamento de bandeiras em frente à Prefeitura, followed por visitas a diferentes regiões do município.

Entre as entregas realizadas, destaca-se a nova Unidade Básica de Saúde em Pedro Tibúrcio, quadras esportivas nos povoados de Pedra e Curral Falso, além da pavimentação de vias locais. No Distrito de Vila Rodrigues, foram entregues o CMEI Agnor Macedo e a Base do SAMU. A gestão municipal também anunciou a modernização das Avenidas Oliveira Brito e Evência Brito, reformas em praças públicas e licitações para pavimentação em 15 povoados.

Os planos de infraestrutura incluem a construção de 10 km de asfalto ligando a sede ao Povoado Poço, 7 km de solo-cimento no Povoado Veríssimo e a implantação do sistema de esgotamento sanitário na sede. Na área habitacional, foi anunciada a construção de 300 casas populares no bairro João do Alto por meio do programa Minha Casa, Minha Vida. As ações contemplam saúde, educação, esporte, mobilidade, moradia e saneamento.', 'https://api.proradiobr.com/imagens-publicas/ribeira-do-pombal-celebra-93-anos-com-inauguracoes-e-anuncio-de-investimentos.webp', '7d34292b-4217-4571-ba21-f7aa996aa1d3', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-19 22:18:11.009376+00', 121, true, 'Ribeira do Pombal celebra 93 anos com obras e investimentos', NULL),
  ('f5fba2a5-e30e-4bdb-8d23-fd72088e79c2', 'TRE-SE define regras para wind banners nas Eleições 2026 em Sergipe', 'tre-se-define-regras-para-wind-banners-nas-eleicoes-2026-em-sergipe', 'TRE-SE regulamenta wind banners para 2026, impondo multas por irregularidades e obstrução de vias públicas em Sergipe.', 'O Tribunal Regional Eleitoral de Sergipe (TRE-SE) publicou novas normas que regulamentam o uso de wind banners nas Eleições 2026. A medida visa garantir a organização do espaço público, a segurança dos pedestres e a conformidade com as diretrizes nacionais do Tribunal Superior Eleitoral (TSE). As regras estabelecem limites técnicos para a instalação e a manutenção desses materiais de propaganda eleitoral, impondo a responsabilidade direta aos partidos políticos e às coligações pela elaboração e fixação das peças.

Conforme as novas diretrizes, a obstrução de calçadas, vias públicas ou a colocação de estruturas que comprometam a circulação de pessoas e veículos será considerada propaganda irregular. A fiscalização será intensificada, e as irregularidades identificadas poderão resultar em multas aos responsáveis. A iniciativa busca prevenir conflitos entre concorrentes e evitar danos à infraestrutura urbana, assegurando que a campanha eleitoral transcorra dentro dos limites legais e sem prejudicar a rotina da população sergipana.', 'https://api.proradiobr.com/imagens-publicas/tre-se-define-regras-para-wind-banners-nas-eleicoes-2026-em-sergipe.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-20 13:56:49.678173+00', 1004, true, 'TRE-SE define regras para wind banners nas Eleições 2026', 'TRE-SE regulamenta uso de wind banners para 2026, estabelecendo normas de instalação e prevendo multas por irregularidades em Sergipe.'),
  ('f786775a-b8e8-42f8-b2af-a22e31b05f08', 'Justiça condena Jorge & Mateus a pagar R$ 50 mil por agressão em Americana', 'justica-condena-jorge-mateus-a-pagar-r-50-mil-por-agressao-em-americana', 'Justiça condenou Jorge & Mateus a pagar R$ 50 mil a maquiadores por agressão e uso indevido de materiais durante show em Americana, SP.', 'A Justiça condenou a dupla sertaneja Jorge & Mateus a pagar indenização de R$ 50 mil aos maquiadores Nathalia Magalhães da Silva e Pedro Henrik Meira da Silva. O processo, movido após um episódio ocorrido na Festa do Peão de Americana, em São Paulo, envolveu acusações de agressão física, uso não autorizado de materiais profissionais e cárcere privado.

Segundo o relato apresentado ao tribunal, os profissionais chegaram ao evento às 20h02 e apenas acessaram o camarim às 22h35. Após serem retirados do espaço, permaneceram cerca de quatro horas em um corredor sem acesso a água ou alimentação, percebendo que não seriam chamados para trabalhar. Ao retornarem para buscar pertences, encontraram equipamentos utilizados por integrantes da equipe, incluindo a esposa de Jorge, Rachel Boscatti. Ao tentar registrar a situação, Nathalia alegou ter sido agredida pelo produtor Willian Pereira Clemente e impedida de sair do local até a chegada da Polícia Militar. Laudo pericial confirmou lesão corporal. A defesa da dupla e do produtor negou as acusações de agressão, classificando o incidente como um conflito pontual, mas a Justiça reconheceu o tratamento degradante e a lesão, fixando o valor da indenização total em R$ 50 mil. Até o momento, a assessoria da dupla não se manifestou publicamente sobre a decisão judicial.', 'https://api.proradiobr.com/imagens-publicas/justica-condena-jorge-mateus-a-pagar-r-50-mil-por-agressao-em-americana.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-20 13:58:52.728943+00', 1006, true, 'Justiça condena Jorge & Mateus a pagar R$ 50 mil por agressão', 'Dupla sertaneja foi condenada a indenizar maquiadores por agressão e cárcere privado durante espetáculo na Festa do Peão de Americana.'),
  ('6a789c96-32c9-47e5-bda6-adbe05fb8536', 'Prefeitura de Ribeira do Pombal lança campanha "Festa de Outubro, Cada Um na Sua" para orientar sobre regras', 'prefeitura-de-ribeira-do-pombal-lanca-campanha-festa-de-outubro-cada-um-na-sua', 'A Prefeitura de Ribeira do Pombal iniciou a campanha “Festa de Outubro, Cada Um na Sua” para informar moradores e visitantes sobre as regras do evento. A iniciativa visa orientar sobre acesso de adolescentes, restrição etária em camarotes e proibição de venda de álcool a menores, promovendo uma festa segura e organizada.', 'A Prefeitura de Ribeira do Pombal lançou uma nova campanha de comunicação intitulada “Festa de Outubro, Cada Um na Sua”. A iniciativa, idealizada pelo Departamento de Comunicação (DECOM) em parceria com órgãos de proteção e segurança, tem como objetivo principal orientar moradores e visitantes sobre as regras de acesso e proteção durante o evento. A proposta visa transformar informações importantes em conteúdos de fácil compreensão e compartilhamento, garantindo que o público possa desfrutar da festa com segurança, respeitando as normas estabelecidas para cada espaço e faixa etária.

Entre os pontos destacados pela campanha estão as regras de acesso de adolescentes de 16 e 17 anos, que poderão participar da área geral da Festa de Outubro mediante apresentação de documento oficial de identificação. Contudo, o Camarote Open Bar é restrito a maiores de 18 anos, proibindo a entrada e permanência de menores nesse espaço. A campanha também enfatiza a proibição da venda, fornecimento ou entrega de bebidas alcoólicas a menores de 18 anos, além de divulgar canais de proteção como o Disque 100, Polícia Militar (190) e Conselho Tutelar. A comunicação será veiculada em diversas plataformas, incluindo redes sociais, sites, cartazes, materiais informativos e telões durante o evento.', 'https://api.proradiobr.com/imagens-publicas/prefeitura-de-ribeira-do-pombal-lanca-campanha-festa-de-outubro-cada-um-na-sua.webp', '7d34292b-4217-4571-ba21-f7aa996aa1d3', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-21 13:25:26.178626+00', 118, true, 'Ribeira do Pombal: Campanha orienta sobre regras da Festa de Outubro', NULL),
  ('9d46674f-ea9d-41eb-848f-354476bbbe23', 'Homem de 55 anos é encontrado morto em Banzaê; caso registrado como morte a esclarecer', 'homem-de-55-anos-e-encontrado-morto-em-banzae-caso-registrado-como-morte-a', 'Um homem de 55 anos, José Domingos dos Santos Ferreira, foi encontrado morto no Povoado Baixão, zona rural de Banzaê, na última sexta-feira. A Polícia Militar e o SAMU estiveram no local. O caso foi registrado como morte a esclarecer, sem indícios de crime.', 'José Domingos dos Santos Ferreira, um homem de 55 anos, foi encontrado sem vida na noite da última sexta-feira, dia 18, no Povoado Baixão, área rural do município de Banzaê. A Polícia Militar foi acionada para o local por volta das 18h48, após o corpo ser descoberto na residência.

Ao chegarem ao endereço, os policiais encontraram a vítima deitada em uma rede. Uma equipe do Serviço de Atendimento Móvel de Urgência (SAMU) também se deslocou e confirmou o óbito. Segundo relatos de familiares, José Domingos possuía um histórico médico de epilepsia e fazia uso frequente de bebidas alcoólicas. O corpo foi posteriormente encaminhado ao Departamento de Polícia Técnica (DPT) para a realização dos exames periciais necessários. O caso foi oficialmente registrado pelas autoridades como morte a esclarecer, sem indícios de crime até o momento.', 'https://imagemlink.cleissoncardoso.com/uploads/ddbc74cd-3a62-4008-b7f0-0e1172db988f.png', '1fd8f094-c10e-4a49-a50a-01fdc88cda45', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-21 14:32:52.701814+00', 1037, true, 'Homem de 55 anos encontrado morto em Banzaê; sem indícios de crime', 'José Domingos dos Santos Ferreira, 55 anos, foi encontrado sem vida no Povoado Baixão, zona rural de Banzaê. O caso foi registrado como morte a esclarecer, sem indícios de crime.'),
  ('583d60ca-f684-425e-932d-d6046cf87daf', 'Pesquisa Nexus/BTG aponta Lula com 40% e Flávio Bolsonaro com 37% no 1º turno', 'pesquisa-nexusbtg-aponta-lula-com-40-e-flavio-bolsonaro-com-37-no-1-turno', 'Levantamento da Nexus/BTG coloca Lula com 40% e Flávio Bolsonaro com 37% na disputa presidencial de 2026, dentro da margem de erro.', 'Pesquisa da Nexus/BTG, divulgada nesta segunda-feira (21), indica o presidente Luiz Inácio Lula da Silva (PT) com 40% das intenções de voto na simulação para o primeiro turno das eleições de 2026. O senador Flávio Bolsonaro (PL) registra 37% da preferência, resultado que configura empate técnico dentro da margem de erro do levantamento.

Na sequência, o escritor Augusto Cury (Avante) pontua 6%, seguido por Ronaldo Caiado (PSD) com 5% e Renan Santos (Missão) com 3%. Romeu Zema (Novo) e Samara Martins (UP) aparecem com 1% cada. Rui Costa Pimenta (PCO), Hertz Dias (PSTU), Edmilson Costa (PCB), Wilson Grassi (Democrata) e Clariana Barão (DC) não pontuaram. Do total de entrevistados, 4% declararam voto branco, nulo ou em nenhum candidato, enquanto 2% não souberam responder.

O levantamento ouviu 2.006 eleitores por telefone entre os dias 18 e 20 de setembro. A margem de erro é de dois pontos percentuais, para mais ou para menos, com intervalo de confiança de 95%. A pesquisa foi contratada pelo Banco BTG Pactual e está registrada no TSE sob o protocolo BR-00485/2026.', 'https://api.proradiobr.com/imagens-publicas/pesquisa-nexusbtg-aponta-lula-com-40-e-flavio-bolsonaro-com-37-no-1-turno.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-21 14:59:46.114589+00', 1006, true, 'Pesquisa Nexus/BTG: Lula tem 40% e Flávio, 37% em 2026', 'Pesquisa Nexus/BTG aponta Lula com 40% e Flávio Bolsonaro com 37% no 1º turno de 2026. Augusto Cury aparece em terceiro lugar com 6%.'),
  ('a4494e83-5e75-4036-8ee2-501bec600f15', 'Criança de 4 anos morre engasgada com carne em Ribeira do Amparo', 'crianca-de-4-anos-morre-engasgada-com-carne-em-ribeira-do-amparo', 'Uma criança de 4 anos, Ana Luiza Ferreira de Santana, faleceu em Ribeira do Amparo após se engasgar com um pedaço de carne. Apesar dos esforços de familiares e da equipe médica, a obstrução das vias aéreas foi fatal.', 'Uma criança de apenas quatro anos de idade, identificada como Ana Luiza Ferreira de Santana, morreu na noite da última sexta-feira (18) em Ribeira do Amparo, Bahia. A menina deu entrada na emergência da Unidade de Saúde da cidade já sem sinais vitais, após ter se engasgado com um pedaço de carne.

De acordo com informações de familiares, o alimento obstruiu as vias aéreas, culminando na morte por asfixia. Embora tenha havido tentativas de retirada por parte dos parentes e, posteriormente, manobras de ressuscitação realizadas pela equipe médica na Unidade, todos os esforços para salvar a vida da criança foram sem sucesso.', 'https://imagemlink.cleissoncardoso.com/uploads/92bc2e2f-5a50-4d96-bcf0-507b323b48e3.png', '6b283438-a9a3-4742-8705-7cfed6acfd49', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-21 17:26:10.880944+00', 1024, true, 'Criança de 4 anos morre engasgada com carne em Ribeira do Amparo-BA', 'Uma menina de 4 anos, Ana Luiza Ferreira de Santana, faleceu em Ribeira do Amparo após se engasgar com carne. Familiares e médicos tentaram salvá-la, mas não houve sucesso.'),
  ('4fcece36-94ed-4c5e-bdcf-cdd507495016', 'Presidente nacional do União Brasil é acusado de agressão por influenciadora em São Paulo', 'presidente-nacional-do-uniao-brasil-e-acusado-de-agressao-por-influenciadora-em', 'Presidente nacional do União Brasil, Antônio Rueda, é acusado de agressão física e psicológica por influenciadora em vídeo de hotel em SP.', 'O presidente nacional do União Brasil e candidato a deputado federal pelo Rio de Janeiro, Antônio Rueda, foi alvo de uma acusação de agressão por parte da influenciadora de moda Luana Delledove. A denúncia foi feita em um vídeo gravado em um quarto de hotel em São Paulo, onde a influenciadora alega ter sofrido violência física e psicológica por parte do dirigente partidário.

No registro audiovisual, Luana Delledove afirma estar há mais de um ano sendo submetida a uma rotina de violência psicológica e mostra marcas vermelhas no lençol da cama, que aparentam ser sangue. Ela também relata que Rueda estaria mantendo um relacionamento extraconjugal enquanto já possuía uma amante. O vídeo, que apresenta diversos cortes, mostra o momento em que Rueda tenta sair do quarto e é contido pela influenciadora. Rueda é casado com a socialite Flor Rueda. Ao encerrar a gravação, Luana expressa temor pelas consequências que a situação pode trazer para a sua família.', 'https://api.proradiobr.com/imagens-publicas/presidente-nacional-do-uniao-brasil-e-acusado-de-agressao-por-influenciadora-em.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-21 19:46:39.666599+00', 1010, true, 'Presidente do União Brasil é acusado de agressão por influenciadora', 'Antônio Rueda, presidente nacional do União Brasil, é acusado de agressão por influenciadora em vídeo gravado em hotel em São Paulo.'),
  ('5487c63e-edff-4b50-8c43-d27ebef364d1', 'Ministro anuncia leilão das BRs 324 e 116 para 17 de dezembro e promete pedágio abaixo de R$ 10', 'ministro-anuncia-leilao-das-brs-324-e-116-para-17-de-dezembro-e-promete-pedagio', 'Ministro dos Transportes confirma leilão das BRs 324 e 116 para dezembro, com pedágio previsto abaixo de R$ 10 e novas regras de fiscalização.', 'O ministro dos Transportes, George Santoro, confirmou que o leilão para a escolha da nova concessionária das rodovias BR-324 e BR-116 ocorrerá em 17 de dezembro. Após o certame, a assinatura do contrato está prevista para ocorrer entre março e abril de 2027. Santoro ressaltou que a nova gestão busca elevar o padrão de serviço, comparando a futura operação à qualidade observada em rodovias como a Dutra e a Fernão Dias, visando beneficiar o fluxo intenso de veículos entre Feira de Santana e Salvador.

Sobre a tarifa, o ministro declarou que o valor do pedágio ficará abaixo de R$ 10, representando o menor preço entre as concessões federais, com isenção total para motociclistas. A nova política prevê incentivos para a antecipação de investimentos e mecanismos rígidos de fiscalização, com verificações trimestrais por auditores independentes; em caso de duas infrações contratuais, a concessão será revogada. Atualmente, o DNIT mantém serviços emergenciais de sinalização e recuperação do pavimento, tendo realizado a fresagem de cerca de 350 quilômetros da BR-324 para eliminar buracos e preparar a via para a nova administração.', 'https://api.proradiobr.com/imagens-publicas/ministro-anuncia-leilao-das-brs-324-e-116-para-17-de-dezembro-e-promete-pedagio.webp', '91925efe-8c0d-42a7-8e21-1d167b8f670b', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-21 21:17:41.262001+00', 1008, true, 'Leilão das BRs 324 e 116 será em dezembro com pedágio abaixo de R$ 10', 'Ministro dos Transportes confirma data do leilão das rodovias BR-324 e BR-116, prometendo padrão de serviço elevado e pedágio inferior a R$ 10.'),
  ('23c80b7f-6826-4dae-b7e8-be9c7540d27d', 'SC: Helicóptero com Rick e empresário perde contato na rota para SP; buscas em andamento', 'sc-helicoptero-com-rick-e-empresario-perde-contato-na-rota-para-sp-buscas-em', 'Rick e o empresário Bruno Avelar estão desaparecidos após helicóptero perder contato na rota de Santa Catarina para São Paulo. Equipes de resgate buscam a aeronave na região.', 'O cantor Rick, da dupla com Renner, e o empresário Bruno Avelar estão desaparecidos após um helicóptero perder o contato com as autoridades nesta segunda-feira (21/9). A aeronave decolou de Santa Catarina com destino à capital paulista. A assessoria de imprensa do artista confirmou o desaparecimento, e o Corpo de Bombeiros de Santa Catarina reportou a queda de um helicóptero na região durante o mesmo intervalo de tempo.

Equipes de busca e resgate foram acionadas imediatamente para localizar a aeronave. Cerca de 20 socorristas se deslocam para o último ponto em que o sinal foi registrado. Segundo as autoridades, as fortes chuvas e ventos que atingiram a região podem ter interferido na perda do contato. Até o momento, não há informações atualizadas sobre o paradeiro dos ocupantes ou resíduos da aeronave.

A perda do sinal ocorreu durante o deslocamento para São Paulo. Rick, nascido em 1966 no Tocantins, é conhecido por sucessos como "Ela é Demais" e por sua atuação como compositor e produtor no gênero sertanejo. O empresário Bruno Avelar atua como coach e palestrante. As operações de resgate continuam em andamento.', 'https://api.proradiobr.com/imagens-publicas/sc-helicoptero-com-rick-e-empresario-perde-contato-na-rota-para-sp-buscas-em.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-21 21:52:29.912004+00', 1015, true, 'Rick e empresário desaparecem após queda de helicóptero em SC', 'Helicóptero com Rick e Bruno Avelar perdeu contato na rota SC-SP. Bombeiros confirmam queda e equipes buscam os desaparecidos na região.'),
  ('efcff8d0-5506-405b-9b1d-391d2cbcb59d', 'Veículo desgovernado colide com duas motos após pular canteiro no centro de Cícero Dantas', 'veiculo-desgovernado-colide-com-duas-motos-apos-pular-canteiro-no-centro-de', 'Um veículo Uno Mille desgovernado colidiu com duas motos estacionadas no centro de Cícero Dantas nesta segunda-feira (21). O acidente ocorreu após o carro pular um canteiro. Apesar do susto e do impacto, ninguém ficou ferido no incidente.', 'Um acidente de trânsito foi registrado por volta das 10h desta segunda-feira (21) na Avenida Nossa Senhora do Bom Conselho, centro de Cícero Dantas, Bahia. Um veículo modelo Uno Mille colidiu com duas motocicletas que estavam estacionadas em frente às Óticas Real. Segundo informações de testemunhas no local, o condutor descia a avenida sentido Banco do Brasil quando o carro, possivelmente devido a um problema mecânico, teria acelerado bruscamente. Assustado, o motorista teria inclinado o veículo em direção ao canteiro central na tentativa de escorá-lo e controlar a velocidade.

Contrariando a intenção do condutor, o veículo acabou pulando o canteiro e invadiu a contramão, atingindo as duas motos que estavam corretamente estacionadas. O repórter Jefferson Oliveira esteve no local para registrar as imagens do ocorrido. A Guarda Civil Municipal (GCM) também compareceu para apurar os fatos iniciais e regularizar o trânsito na área. Até o momento da permanência da equipe no local, não foi observada a presença do condutor do Uno Mille nem dos proprietários das motocicletas. Apesar do impacto, felizmente, não houve registro de feridos, conforme as informações preliminares.', 'https://imagemlink.cleissoncardoso.com/uploads/aae6aca6-f7a5-4f5f-8798-f5346aab713c.png', '1bff82e6-6033-4d75-8d04-e26d976c0a05', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-21 22:00:02.48783+00', 1024, true, 'Acidente em Cícero Dantas: Carro desgovernado colide com motos no centro', 'Um veículo Uno Mille colidiu com duas motocicletas estacionadas no centro de Cícero Dantas nesta segunda-feira (21), após pular um canteiro. Não houve feridos no incidente.'),
  ('43b7ac5b-0851-4d35-8408-70caa78c83ca', 'Mulher é presa em flagrante por furto de celular durante festa em Nova Soure', 'mulher-e-presa-em-flagrante-por-furto-de-celular-durante-festa-em-nova-soure', 'Uma mulher foi presa em flagrante em Nova Soure (BA) após furtar um celular durante uma festa. A vítima rastreou o aparelho, que foi encontrado com a suspeita escondido entre os seios, levando à sua prisão e encaminhamento à delegacia.', 'Uma mulher foi presa em flagrante na madrugada do último domingo (20) em Nova Soure, Bahia, acusada de furtar um aparelho celular durante um evento festivo na cidade. A ação ocorreu após a vítima procurar policiais militares e relatar o furto de um Smartphone iPhone 17 Pro Max. O rastreamento do aparelho indicava que ele estava no local da festa, para onde os militares se dirigiram. No evento, a suspeita foi identificada e, em uma primeira abordagem, negou a autoria do furto, e o celular não foi encontrado em sua bolsa.

Por volta das 4h30, o sinal de GPS do aparelho começou a se mover simultaneamente com a suspeita, levando a uma segunda abordagem. Nesse momento, a mulher, identificada pelas iniciais M.B de S, confirmou que estava com o aparelho, escondido entre os seios. Diante do flagrante, a mulher e o celular recuperado foram encaminhados à Delegacia de Polícia Civil de Nova Soure para as providências legais cabíveis.', 'https://imagemlink.cleissoncardoso.com/uploads/097051d1-b1b9-49bd-8246-2137899671e0.png', '6f2a37a5-5762-4f9e-9150-7c8267cd5ac4', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-22 11:53:03.945299+00', 1026, true, 'Mulher é presa em Nova Soure por furtar iPhone 17 Pro Max em festa', 'Uma mulher foi presa em flagrante em Nova Soure (BA) acusada de furtar um iPhone 17 Pro Max durante um evento festivo. O celular foi rastreado e encontrado escondido com a suspeita.'),
  ('3f0cfae9-806b-4068-9655-c05025b96b0c', 'Prefeito de Ribeira do Pombal que apoia Jerônimo diz que oposição faz “discurso maldoso” e não conhece realidade da Bahia', 'prefeito-de-ribeira-do-pombal-que-apoia-jeronimo-diz-que-oposicao-faz-discurso-maldoso-e-nao-conhece-realidade-da-bahia', '“Um discurso muito maldoso que a gente vê hoje. São 417 cidades na Bahia que o governador está sempre presente. É um governo que está em todo município, que gosta de gente”, afirmou Eriksson, reafirmando apoio à reeleição de Jerônimo Rodrigues. “Ele [ACM Neto] não conhece as demandas de cada localidade. Não sabe de perto os anseios da sociedade”, acrescentou. ', '
O prefeito de Ribeira do Pombal, Eriksson Silva, criticou nesta segunda-feira (21) o discurso de que prefeitos não seriam necessários para as eleições. Ao defender a parceria entre as diferentes esferas de governo, ele afirmou que a oposição, encabeçada por ACM Neto, não conhece de perto as demandas da Bahia. 

“Um discurso muito maldoso que a gente vê hoje. São 417 cidades na Bahia que o governador está sempre presente. É um governo que está em todo município, que gosta de gente”, afirmou Eriksson, reafirmando apoio à reeleição de Jerônimo Rodrigues. “Ele [ACM Neto] não conhece as demandas de cada localidade. Não sabe de perto os anseios da sociedade”, acrescentou. 

O prefeito destacou investimentos realizados em Ribeira do Pombal, como os R$ 135 milhões para o abastecimento de água, a ampliação do Hospital Geral Santa Tereza e mais de R$ 25 milhões em pavimentação. Segundo ele, as obras mostram a importância da articulação entre Estado, União e municípios.

“Município sozinho não caminha só. Então precisa ter a parceria tanto do Governo do Estado, como também do Governo Federal, para os municípios poderem andar e se desenvolver”, disse.', 'https://mkbnqyhvaozqfpmcyoyw.supabase.co/storage/v1/object/public/imagens/noticias/1790080364544_k3l0t1y.webp', '7d34292b-4217-4571-ba21-f7aa996aa1d3', NULL, '2026-09-22 12:33:24.181+00', 5458, true, '', ''),
  ('61255fcb-6924-4a77-a4db-8fa2ed5b8693', 'Família dos EUA entra para o Livro dos Recordes após cinco gerações nascerem no mesmo dia', 'familia-dos-eua-entra-para-o-livro-dos-recordes-apos-cinco-geracoes-nascerem-no', 'Cinco gerações da mesma família americana nasceram no dia 14 de setembro, fato reconhecido pelo Guinness World Records após o nascimento de Arthur Bell.', 'Uma família dos Estados Unidos estabeleceu um recorde mundial ao ter cinco integrantes de gerações distintas nascidos no dia 14 de setembro. A marca foi reconhecida pelo Guinness World Records após o nascimento de Arthur Bell, no ano passado, completando uma sequência iniciada em 1907.

A linhagem começa com Wilber Harlow, nascido em 1907, seguido pela filha Addie em 1927, o neto Fred em 1950, a bisneta Emma em 1986 e o trineto Arthur no ano anterior. Segundo a emissora KMTV, afiliada à CBS, a família sempre considerou a coincidência curiosa, mas nunca imaginou que poderia se tornar um recorde oficial.

Fred Harlow relata que os parentes brincavam sobre a possibilidade de bater a marca, mas não enviaram a documentação até a chegada do quinto integrante. Emma, mãe de Arthur, lembra que sua avó costumava afirmar que ela precisava ter um filho no dia 14 de setembro. Além da data idêntica, a família observou que os gêneros dos integrantes se alternam na sequência.

Apesar da conquista, Emma e Fred afirmam não querer criar pressão sobre a próxima geração. Por enquanto, os cinco aniversariantes se reúnem anualmente para comemorar a data, que já atravessou mais de um século de história familiar.', 'https://api.proradiobr.com/imagens-publicas/familia-dos-eua-entra-para-o-livro-dos-recordes-apos-cinco-geracoes-nascerem-no.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-22 13:06:15.040011+00', 1005, true, 'Família dos EUA bate recorde mundial com cinco gerações nascidas no mesmo dia', 'Cinco gerações de uma família americana nasceram no dia 14 de setembro. A sequência, iniciada em 1907, foi reconhecida pelo Guinness World Records.'),
  ('812e31b1-8373-4497-969e-3918bd16c7ef', 'PF aponta ACM Neto como líder político de organização criminosa na Operação Overclean', 'pf-aponta-acm-neto-como-lider-politico-de-organizacao-criminosa-na-operacao', 'A PF aponta ACM Neto como líder político de organização criminosa na Operação Overclean. Foram identificadas 232 chamadas entre ele e o Rei do Lixo.', 'A Polícia Federal (PF) identificou 232 chamadas telefônicas entre Antonio Carlos Peixoto de Magalhães Neto, conhecido como ACM Neto, e o empresário apelidado de Rei do Lixo. O candidato ao governo da Bahia pelo União Brasil figura, segundo as investigações, como o líder político de uma organização criminosa suspeita de desviar recursos públicos em diversos municípios pelo país.

As apurações fazem parte da Operação Overclean, que investiga a prática de fraudes e desvios em contratos públicos. Durante a investigação, foram analisados registros de comunicações que teriam coordenado as ações do esquema. A defesa de ACM Neto não foi localizada para comentar as informações preliminares divulgadas pela corporação nesta fase do inquérito.', 'https://api.proradiobr.com/imagens-publicas/pf-aponta-acm-neto-como-lider-politico-de-organizacao-criminosa-na-operacao.webp', '91925efe-8c0d-42a7-8e21-1d167b8f670b', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-22 14:26:42.907747+00', 1021, true, 'PF aponta ACM Neto como líder de organização na Operação Overclean', 'A Polícia Federal aponta ACM Neto como líder político de esquema investigado na Operação Overclean, que apura desvios de recursos públicos.'),
  ('2de0e6a5-2ddb-4131-8c1c-62d628b87a3e', 'Eleição presidencial de 2026: analistas avaliam chances de definição no primeiro turno', 'eleicao-presidencial-de-2026-analistas-avaliam-chances-de-definicao-no-primeiro', 'Analistas avaliam cenários para a eleição presidencial de 2026, debatendo a viabilidade de uma vitória no primeiro turno em 4 de outubro ou a necessidade de um segundo turno em 25 de outubro.', 'Com 12 dias para a votação de 4 de outubro, a possibilidade de a disputa pelo Palácio do Planalto ser decidida no primeiro turno mobiliza campanhas e eleitores. Para que isso ocorra, um candidato precisa alcançar mais da metade dos votos válidos, excluindo brancos e nulos. A definição depende, portanto, não apenas do desempenho do líder nas pesquisas, mas também da abstenção e do comportamento de quem opta por anular o voto.

Analistas apontam que o cenário permanece em aberto. A cientista política Maria Almeida, da FGV, destaca que a mobilização dos indecisos será o fator decisivo. Já Guilherme Russo, diretor de Inteligência da Quaest, considera improvável uma vitória antecipada, citando a necessidade de Flávio Bolsonaro capturar votos de outros candidatos da direita. O desempenho nas últimas 48 horas antes da votação é visto como crucial para consolidar um resultado. Caso nenhum candidato atinja a maioria absoluta, o segundo turno será realizado em 25 de outubro, vencendo quem obtiver a maioria simples dos votos.', 'https://api.proradiobr.com/imagens-publicas/eleicao-presidencial-de-2026-analistas-avaliam-chances-de-definicao-no-primeiro.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-22 15:42:35.178361+00', 1007, true, 'Eleição 2026: analistas debatem chances de vitória no 1º turno', 'Especialistas avaliam a possibilidade de a eleição presidencial de 2026 ser decidida no primeiro turno, considerando votos válidos e abstenção.'),
  ('c08ee059-ac62-4714-bf4f-86f0ee7f894b', 'Bombeiros localizam helicóptero com Rick Sollo e confirmam cinco mortes', 'bombeiros-localizam-helicoptero-com-rick-sollo-e-confirmam-cinco-mortes', 'Bombeiros de Santa Catarina localizaram o helicóptero de Rick Sollo e confirmaram cinco mortes. A operação envolveu drones, cães de busca e aeronaves.', 'O Corpo de Bombeiros Militar de Santa Catarina (CBMSC) localizou os destroços da aeronave onde estava o cantor Rick Sollo, da dupla com Renner, além de mais três pessoas. Cinco mortes foram confirmadas após a identificação dos corpos no local do acidente.

Segundo informações obtidas pelo Metrópoles com fontes que acompanham as buscas, a localização ocorreu na área onde o helicóptero sumiu do radar na tarde de segunda-feira (21/9). A operação contou com o apoio da aeronave Arcanjo 3, 40 bombeiros, dois cães de busca e resgate, mais de 10 viaturas e drones com capacidade de identificação térmica. Após a localização, os bombeiros iniciaram a descida ao local para o resgate das vítimas, que será seguido por perícias da Polícia Científica e investigações dos órgãos competentes.', 'https://api.proradiobr.com/imagens-publicas/bombeiros-localizam-helicoptero-com-rick-sollo-e-confirmam-cinco-mortes.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-22 15:43:14.590896+00', 1010, true, 'Bombeiros acham helicóptero de Rick Sollo e confirmam 5 mortes', 'CBMSC localizou destroços do helicóptero do cantor Rick Sollo em SC e confirmou cinco mortes. Buscas envolveram drones e cães.'),
  ('351b9977-3a34-46eb-83bc-d2970b3ab32c', 'Caminhão carregado de laranjas tomba na BR-410 em Ribeira do Pombal', 'caminhao-carregado-de-laranjas-tomba-na-br-410-em-ribeira-do-pombal', 'Um caminhão carregado de laranjas tombou na BR-410, em Ribeira do Pombal, na noite de segunda-feira. O motorista, Roberto (46), relatou ter desviado de outros veículos para evitar uma colisão, o que causou o tombamento.', 'Um caminhão transportando laranjas tombou na noite da última segunda-feira, dia 21, na rodovia BR-410. O incidente ocorreu na chegada da cidade de Ribeira do Pombal, nas imediações de um motel. O veículo estava em uma viagem longa, vindo de Lagarto, em Sergipe, e tinha como destino final a cidade de Fortaleza, no Ceará.

O motorista, identificado como Roberto, de 46 anos, relatou que o acidente foi resultado de uma manobra para evitar uma colisão mais grave. Segundo sua versão, uma carreta teria descido a ladeira em direção a três veículos de passeio. Para impedir o choque direto, Roberto teria desviado, atingindo lateralmente um dos veículos. Em seguida, o caminhão saiu da pista e tombou em uma ribanceira.', 'https://imagemlink.cleissoncardoso.com/uploads/6149e5e5-e8a9-4e8e-8df7-9793a7dd9b3a.png', '7d34292b-4217-4571-ba21-f7aa996aa1d3', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-22 17:35:47.09066+00', 1028, true, 'Caminhão com laranjas tomba na BR-410 em Ribeira do Pombal', 'Um caminhão carregado de laranjas tombou na BR-410, na chegada de Ribeira do Pombal. O motorista informou ter feito manobra para evitar colisão.'),
  ('1a01b2ed-5433-431a-a2da-c0b5fbc108ea', 'Câmeras de monitoramento registram mulher suspeita de aplicar golpe em Ribeira do Pombal', 'cameras-de-monitoramento-registram-mulher-suspeita-de-aplicar-golpe-em-ribeira', 'Imagens de câmeras mostram mulher suspeita de aplicar golpe em Ribeira do Pombal. Ela teria subtraído dinheiro de uma vítima no centro da cidade.', 'Imagens capturadas por câmeras de monitoramento mostram uma mulher caminhando pelo centro de Ribeira do Pombal, na Bahia, e a tornam alvo de suspeitas por supostos golpes aplicados na última sexta-feira (18). Conforme informações divulgadas, a suspeita teria agido em diversos locais do município durante a manhã.

Segundo o relato, um dos episódios ocorreu em um estabelecimento comercial localizado na Avenida Oliveira Brito. A mulher teria se aproximado de uma vítima, cuja identidade foi preservada, oferecendo-se para realizar uma oração. Aproveitando-se de um momento de distração, ela teria subtraído uma quantia em dinheiro que corresponderia ao salário mensal da vítima. As imagens que flagraram a suspeita circulam nas redes sociais, e as autoridades recomendam que pessoas que reconheçam a mulher ou conheçam seu paradeiro entrem em contato com a polícia para auxiliar nas investigações.', 'https://api.proradiobr.com/imagens-publicas/cameras-de-monitoramento-registram-mulher-suspeita-de-aplicar-golpe-em-ribeira.webp', '7d34292b-4217-4571-ba21-f7aa996aa1d3', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-22 20:16:23.015764+00', 114, true, 'Câmeras flagram suspeita de golpe em Ribeira do Pombal', NULL),
  ('7374ecec-cdec-4bf6-bf30-b3aef5b46c68', 'Prefeitura de Ribeira do Pombal planeja segurança e estrutura da Festa de Outubro', 'prefeitura-de-ribeira-do-pombal-planeja-seguranca-e-estrutura-da-festa-de', 'Prefeitura de Ribeira do Pombal reuniu forças de segurança e técnicos para planejar a Festa de Outubro, com foco em ampliar acessos e garantir estrutura para público de 60 mil pessoas.', 'O prefeito de Ribeira do Pombal, Eriksson Silva, conduziu reuniões nesta terça-feira para definir as estratégias de segurança e infraestrutura da Festa de Outubro, agendada para os dias 9, 10 e 11 de outubro no Estádio Municipal. O encontro reuniu secretários municipais, equipes do Departamento de Controle (DECOM), Engenharia, Procuradoria, além de representantes da CIPE Nordeste, 21ª Companhia Independente de Polícia Militar (CIPM), Corpo de Bombeiros, Guarda Civil Municipal e Polícia Rodoviária Federal (PRF). Entre as principais medidas discutidas, destaca-se a ampliação dos pontos de entrada e a reorganização dos acessos para garantir a fluidez no fluxo de público e reforçar a segurança durante a programação.

Após as discussões teóricas, as autoridades realizaram uma vistoria técnica no estádio, que possui cerca de 15 mil metros quadrados e capacidade estimada para 60 mil pessoas. A logística exige planejamento integrado entre os órgãos envolvidos, especialmente diante da expectativa de um dos maiores públicos da história do evento, que contará com atrações nacionais como Gusttavo Lima. No período da tarde, o prefeito se reuniu com a equipe de infraestrutura para detalhar a montagem do evento, a circulação de pessoas e as estruturas necessárias. A administração municipal busca antecipar demandas para integrar segurança, mobilidade e atendimento, garantindo a melhor experiência para moradores de Ribeira do Pombal e visitantes da região.', 'https://api.proradiobr.com/imagens-publicas/prefeitura-de-ribeira-do-pombal-planeja-seguranca-e-estrutura-da-festa-de.webp', '7d34292b-4217-4571-ba21-f7aa996aa1d3', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-22 20:25:43.675172+00', 112, true, 'Festa de Outubro em Ribeira do Pombal: plano de segurança', NULL),
  ('07180fc9-f879-4268-b7c5-9706cb4a2c84', 'Nova lei aumenta pena para até 10 anos de prisão por furto de combustíveis', 'nova-lei-aumenta-pena-para-ate-10-anos-de-prisao-por-furto-de-combustiveis', 'Lei sancionada pelo governo federal aumenta pena para furto de combustíveis em até dez anos de prisão e tipifica crimes contra a ordem econômica.', 'O governo federal sancionou a lei que endurece as penas para crimes de furto e roubo de combustíveis, norma assinada pelo vice-presidente Geraldo Alckmin e publicada no Diário Oficial da União nesta quarta-feira, 23. A legislação estabelece pena de reclusão de quatro a dez anos, além de multa, para o furto de petróleo, derivados, gás natural, combustíveis líquidos, biocombustíveis e óleos lubrificantes retirados de locais de produção, armazenamento ou transporte.

As sanções podem ser agravadas em até dois terços em casos de rompimento de obstáculos, atuação em grupo ou envolvimento de agentes públicos, especialmente quando o crime resultar em desabastecimento, incêndio, poluição, lesões graves ou morte. A norma também tipifica como crime contra a ordem econômica a aquisição, o transporte, o armazenamento ou a venda de combustíveis de origem ilícita, com pena de até oito anos de reclusão. Servidores públicos envolvidos nessas condutas poderão perder o cargo e ficar inabilitados para o exercício de funções públicas pelo dobro do tempo da pena aplicada.', 'https://api.proradiobr.com/imagens-publicas/nova-lei-aumenta-pena-para-ate-10-anos-de-prisao-por-furto-de-combustiveis.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-23 11:45:41.217975+00', 1006, true, 'Nova lei aumenta pena para furto de combustíveis em até 10 anos', 'Lei sancionada pelo governo endurece penas para furto de combustíveis, prevendo até 10 anos de prisão e crimes contra a ordem econômica.'),
  ('1fd073fb-ee3e-4155-9cb4-6dc2165cce2e', 'Michelle Bolsonaro é internada em Brasília sem previsão de alta por enxaqueca', 'michelle-bolsonaro-e-internada-em-brasilia-sem-previsao-de-alta-por-enxaqueca', 'Ex-primeira-dama está no Hospital DF Star, em Brasília, tratando enxaqueca refratária. Boletim médico confirma internação sem data para alta.', 'A ex-primeira-dama Michelle Bolsonaro (PL) está internada no Hospital DF Star, em Brasília, sem previsão de alta, conforme comunicado em suas redes sociais nesta terça-feira, 22. Segundo o boletim médico, ela deu entrada na unidade com quadro de enxaqueca refratária ao tratamento clínico ambulatorial iniciado há dois meses.

A nota oficial, assinada pelo chefe da equipe médica Brasil Caiado, pelo anestesiologista João Francisco Volpe Júnior e pelo diretor-geral Allisson B. Barcelos Borges, informa que a paciente segue em tratamento clínico especializado. Em agosto, Michelle também foi internada no mesmo hospital por problemas de enxaqueca, o que a impediu de participar do lançamento da candidatura de Bia Kicis (PL) ao Senado. Naquela ocasião, após 16 dias de sintomas e uma tomografia computadorizada, foi identificado um caso de cefaleia refratária, levando a realização de um procedimento de bloqueio anestésico dos nervos cranianos.', 'https://api.proradiobr.com/imagens-publicas/michelle-bolsonaro-e-internada-em-brasilia-sem-previsao-de-alta-por-enxaqueca.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-23 11:56:36.500022+00', 1009, true, 'Michelle Bolsonaro internada em Brasília por enxaqueca', 'Michelle Bolsonaro está internada no Hospital DF Star, em Brasília, sem previsão de alta. Boletim médico confirma tratamento por enxaqueca refratária.'),
  ('fd6d3061-c7dd-4793-aa55-e95584fb2877', 'Três homens são presos por embriaguez e suspeita de saque de carga em Cícero Dantas e outras cidades da Bahia', 'tres-homens-sao-presos-por-embriaguez-e-suspeita-de-saque-de-carga-em-cicero', 'A PRF prendeu três homens na Bahia por embriaguez ao volante e suspeita de saque de carga. As ações ocorreram em Seabra, Cícero Dantas e Vitória da Conquista.', 'Três homens foram presos pela Polícia Rodoviária Federal (PRF) em rodovias da Bahia entre a segunda-feira (21) e a manhã desta terça-feira (22). As ocorrências ocorreram em Seabra, Cícero Dantas e Vitória da Conquista, envolvendo casos de direção sob efeito de álcool e a suspeita de furto de mercadorias após acidente.

Na primeira ocorrência, registrada no km 408 da BR-242, em Seabra, um motorista de veículo de carga foi detido após o teste do etilômetro apontar 0,50 mg de álcool por litro de ar expelido. No mesmo dia, à noite, outro condutor foi preso no km 137 da BR-110, em Cícero Dantas, após envolvimento em um acidente; o bafômetro indicou 0,71 mg de álcool por litro de ar. Ambos foram encaminhados às delegacias locais para as providências legais.

Na manhã desta terça, a PRF atendeu a um tombamento de um caminhão carregado com produtos eletrônicos no km 846 da BR-116, em Vitória da Conquista. Durante o recolhimento de mercadorias espalhadas às margens da rodovia, policiais flagraram um homem transportando itens em um veículo de passeio. O suspeito foi detido e o material apreendido, incluindo móveis e eletrodomésticos, foi apresentado à autoridade competente.', 'https://api.proradiobr.com/imagens-publicas/tres-homens-sao-presos-por-embriaguez-e-suspeita-de-saque-de-carga-em-cicero.webp', '1bff82e6-6033-4d75-8d04-e26d976c0a05', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-23 11:59:19.804219+00', 114, true, 'PRF prende três por embriaguez e suspeita de saque em rodovias da Bahia', NULL),
  ('46dea5f7-a3bc-4bfb-ab1b-a123ba947be4', 'Contrato de R$ 10 milhões gera prejuízo de R$ 6 milhões à prefeitura de Cipó-BA', 'contrato-de-r-10-milhoes-gera-prejuizo-de-r-6-milhoes-a-prefeitura-de-cipo-ba', 'Prefeitura de Cipó acumula prejuízo de R$ 6 milhões em contrato de energia solar de R$ 10 milhões, com obra parada e pagamentos adiantados.', 'A prefeitura de Cipó firmou em setembro de 2024 contrato de quase R$ 10 milhões com a Photonex para instalação de um sistema de energia solar, custo superior à média de mercado para potência semelhante. O município contraiu empréstimo de R$ 10 milhões no Banco do Brasil para cobrir os pagamentos, que atingiram 94% do valor total até julho de 2026, sem a conclusão da obra.

Segundo o Portal Alerta, o terreno destinado à usina permanece sem equipamentos, embora a gestão municipal alegue que 95% do projeto está concluído e que as unidades estão aguardando vistoria da Coelba. A empresa contratada atribui os atrasos à distribuidora de energia, enquanto o prejuízo acumulado do município, somando parcelas do empréstimo e contas de luz, ultrapassa R$ 6 milhões. Tanto a prefeitura quanto a Coelba não se manifestaram até o fechamento da matéria.', 'https://api.proradiobr.com/imagens-publicas/contrato-de-r-10-milhoes-gera-prejuizo-de-r-6-milhoes-a-prefeitura-de-cipo-ba.webp', '3949c67e-3936-409d-9600-28782301730d', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-23 21:18:24.241412+00', 111, true, 'Cipó-BA: Contrato de energia solar gera prejuízo de R$ 6 milhões', NULL),
  ('29533a99-4033-4f23-bd83-e1b6077997fe', 'Adustina completa um ano sem registro de homicídios', 'adustina-completa-um-ano-sem-registro-de-homicidios', 'O município de Adustina, na Bahia, atingiu a marca de um ano sem o registro de homicídios na última segunda-feira (21). O último caso foi em 21 de setembro de 2025, quando Denison Vieira Almeida foi assassinado após um confronto.', 'Adustina, na Bahia, registrou um marco significativo na segurança pública ao completar um ano sem homicídios. A marca foi alcançada na última segunda-feira, dia 21.

O último crime dessa natureza foi documentado em 21 de setembro de 2025. Na ocasião, Denison Vieira Almeida foi vítima de um assassinato por disparo de arma de fogo, após um confronto com Luís Paulo Moraes Vieira. Detalhes adicionais sobre o incidente não foram especificados na informação original.', 'https://api.proradiobr.com/imagens-publicas/adustina-completa-um-ano-sem-registro-de-homicidios.webp', 'eb26fa6f-1d0d-4efd-bdac-6b6fbdd98431', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-23 21:18:31.76993+00', 108, true, 'Adustina (BA) alcança um ano sem registro de homicídios', NULL),
  ('66826fa0-d5b1-4157-88ec-4679b70fb866', 'Setor de apostas se articula no Congresso contra possível MP de Lula sobre bets', 'setor-de-apostas-se-articula-no-congresso-contra-possivel-mp-de-lula-sobre-bets', 'Entidades do setor de apostas online se articulam no Congresso para emendar possível MP de Lula que restringe bets. Setor também avalia judicializar eventuais mudanças.', 'Entidades que representam o setor de apostas online iniciaram articulações no Congresso Nacional em resposta à possibilidade de envio de uma Medida Provisória (MP) pelo presidente Luiz Inácio Lula da Silva. O objetivo é apresentar emendas ao texto para tentar alterar as novas restrições propostas pelo governo federal às casas de apostas e cassinos virtuais.

Segundo informações da coluna de Igor Gadelha, do Metrópoles, os representantes do setor avaliam que a tramitação da medida no Legislativo abrirá espaço para negociações com parlamentares aliados. Além da atuação política, a possibilidade de judicialização das restrições também é considerada pelas empresas. O debate ocorre após Lula declarar a intenção de adotar medidas mais drásticas sobre o tema, com discussões em andamento sobre a eventual proibição de apostas esportivas e jogos online. O setor argumenta que as empresas autorizadas cumpriram processos de regulamentação e pagaram taxas de licença, o que poderia fundamentar questionamentos jurídicos caso as atividades sejam interrompidas.', 'https://api.proradiobr.com/imagens-publicas/setor-de-apostas-se-articula-no-congresso-contra-possivel-mp-de-lula-sobre-bets.webp', '29041cc7-195c-4973-b71d-c3c5e37c70bf', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-24 11:07:18.54689+00', 1006, true, 'Sector de bets se articula no Congresso contra MP de Lula', 'Entidades de apostas online buscam emendas no Congresso contra possível MP de Lula. Setor avalia judicialização e lembra processo de licenciamento.'),
  ('464392c0-b0ce-4dfb-bfe3-2364bf510c21', 'Ribeira do Pombal recebe 13ª edição do Festival Cultureira neste final de semana', 'ribeira-do-pombal-recebe-13-edicao-do-festival-cultureira-neste-final-de-semana', 'Ribeira do Pombal sedia a 13ª edição do Festival Cultureira neste final de semana, como parte das celebrações de aniversário da cidade. O evento reúne mais de mil produtores culturais, destacando a arte, a dança, a música e as tradições locais.', 'Ribeira do Pombal se prepara para receber a 13ª edição do Festival Cultureira neste final de semana. O evento faz parte da programação comemorativa pelo aniversário da cidade e promete ser um grande encontro com a arte, a cultura e as tradições locais. Mais de 1.000 produtores culturais estão envolvidos na iniciativa, que celebra a diversidade cultural do município e reúne manifestações artísticas de diferentes gerações, promovendo a valorização da produção cultural local.

Durante os dois dias de festival, o público terá a oportunidade de acompanhar uma vasta programação que abrange música, dança, apresentações culturais e a degustação de comidas típicas. O Cultureira destaca talentos de todas as idades e diversas expressões artísticas, com foco nos artistas da própria região, que ocupam o centro das atenções. O festival se consolidou como um espaço essencial para revelar novos talentos, preservar as tradições e demonstrar a vitalidade da produção cultural de Ribeira do Pombal, reforçando o lema de ser "feito pelo próprio povo". A expectativa é que o evento atraia milhares de pessoas para celebrar a criatividade e a riqueza cultural da cidade.', 'https://api.proradiobr.com/imagens-publicas/ribeira-do-pombal-recebe-13-edicao-do-festival-cultureira-neste-final-de-semana.webp', '7d34292b-4217-4571-ba21-f7aa996aa1d3', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-24 12:22:40.503023+00', 110, true, 'Ribeira do Pombal: 13ª edição do Festival Cultureira celebra cultura local', NULL),
  ('e2b7d113-93b1-4935-a17e-f4bb2b83891d', 'Justiça Eleitoral proíbe venda e distribuição de bebidas alcoólicas durante as eleições em Ribeira do Pombal, Banzaê e Heliópolis', 'justica-eleitoral-proibe-venda-e-distribuicao-de-bebidas-alcoolicas-durante-as-eleicoes-em-ribeira-do-pombal-banzae-e-heliopolis', 'A Portaria estabelece ainda que o descumprimento poderá resultar em fechamento imediato do estabelecimento, além de outras medidas administrativas, civis e criminais cabíveis, inclusive prisão dos responsáveis, conforme a legislação eleitoral.', 'A Justiça Eleitoral da 110ª Zona Eleitoral da Bahia publicou a Portaria ZE-110 nº 14, de 21 de setembro de 2026, que estabelece a proibição da comercialização e distribuição de bebidas alcoólicas nos municípios de Ribeira do Pombal, Banzaê e Heliópolis durante os períodos definidos para as eleições de 2026.

A medida foi assinada pelo juiz eleitoral Paulo Henrique Santos Santana e abrange bares, restaurantes, lanchonetes, supermercados, barracas e outros estabelecimentos semelhantes.

 Proibição começa no sábado anterior à votação

De acordo com o Art. 1º da Portaria, no primeiro turno, a comercialização e distribuição de bebidas alcoólicas ficam proibidas:

Das 18h do dia 3 de outubro de 2026 até as 21h do dia 4 de outubro de 2026, dia da votação.

Caso haja segundo turno, a mesma restrição será aplicada:

Das 18h do dia 24 de outubro até as 21h do dia 25 de outubro de 2026.

Durante esse período, os estabelecimentos poderão continuar funcionando, mas **não poderão servir bebidas alcoólicas.

A Portaria estabelece ainda que o descumprimento poderá resultar em **fechamento imediato do estabelecimento**, além de outras medidas administrativas, civis e criminais cabíveis, inclusive prisão dos responsáveis, conforme a legislação eleitoral.

 Cartório Eleitoral fará divulgação

O documento também determina que o Cartório Eleitoral dê ampla divulgação à medida, inclusive por meio das rádios locais, para garantir que a população e os estabelecimentos tenham conhecimento prévio da determinação.

A decisão também será comunicada às **Polícias Civil e Militar e ao Ministério Público Eleitoral.

Os estabelecimentos que comercializam bebidas alcoólicas deverão ainda afixar, em local visível, a proibição estabelecida pela Justiça Eleitoral.

A Portaria entra em vigor na data de sua publicação.

Fonte: Portaria ZE-110 nº 14, de 21 de setembro de 2026, Justiça Eleitoral da 110ª Zona Eleitoral.
', 'https://mkbnqyhvaozqfpmcyoyw.supabase.co/storage/v1/object/public/imagens/noticias/1790252779834_rt408a4.webp', '7d34292b-4217-4571-ba21-f7aa996aa1d3', NULL, '2026-09-24 12:26:53.686+00', 515, true, '', ''),
  ('1e77fe28-fe14-41cd-8a5a-650ef5764bb4', 'Homem morre em Adustina após descarga elétrica ao tentar reparar fiação', 'homem-morre-em-adustina-apos-descarga-eletrica-ao-tentar-reparar-fiacao', 'Higor Reis Andrade, de 46 anos, morreu em Adustina na última sexta-feira (18) após sofrer uma descarga elétrica. Ele tentava consertar a fiação de uma rua que havia caído devido às chuvas. Socorrido ao hospital local, Higor não resistiu.', 'Um homem de 46 anos, identificado como Higor Reis Andrade, faleceu na última sexta-feira, dia 18, em Adustina, após sofrer uma descarga elétrica. O incidente ocorreu por volta das 7h, no Loteamento José Aldo, localizado no Centro da cidade. Segundo relatos da polícia, os fios elétricos haviam caído durante as fortes chuvas da madrugada anterior, e Higor estava tentando realizar o reparo da fiação com o auxílio de um vizinho.

Durante o procedimento, Higor Reis Andrade foi atingido pela descarga elétrica e caiu ao chão. O cabo permaneceu preso à sua mão, e o vizinho prontamente utilizou um alicate para cortar o fio e interromper o contato. A vítima foi socorrida e levada ainda com vida para a Unidade Mista Hospitalar de Adustina, mas não resistiu aos ferimentos e veio a óbito no local. A Polícia Militar registrou a ocorrência como morte acidental por descarga elétrica. A Guarda Municipal e a Prefeitura de Adustina também foram acionadas para isolar a área e tomar as providências necessárias em relação à rede elétrica.', 'https://imagemlink.cleissoncardoso.com/uploads/a3cc885e-d0a4-4b9a-802b-c80546aa5804.png', 'eb26fa6f-1d0d-4efd-bdac-6b6fbdd98431', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-24 12:54:43.090365+00', 1023, true, 'Homem morre por choque elétrico ao reparar fiação em Adustina', 'Higor Reis Andrade, de 46 anos, faleceu em Adustina após descarga elétrica enquanto tentava consertar fios caídos por chuvas. Ele foi socorrido, mas não resistiu.'),
  ('1abfadeb-1185-43df-8873-3f4277048978', 'Operação Iceberg prende 11 suspeitos e apreende veículos de luxo em esquema de tráfico na Bahia', 'operacao-iceberg-prende-11-suspeitos-e-apreende-veiculos-de-luxo-em-esquema-de', 'Operação da Polícia Civil na Bahia prende 11 suspeitos de tráfico para elite e bloqueia R$ 200 milhões. Grupo movimentou R$ 9,6 milhões usando redes sociais e PIX.', 'A Polícia Civil da Bahia deflagrou nesta quinta-feira (24) a Operação Iceberg, que resultou na prisão de 11 suspeitos e no bloqueio de até R$ 200 milhões em bens. O grupo, que atuava na venda de entorpecentes para médicos, empresários e advogados, movimentou mais de R$ 9,6 milhões em transações bancárias, segundo a investigação conduzida pelo Departamento de Homicídios e Proteção à Pessoa (DHPP).

O esquema utilizava redes sociais, principalmente o Instagram, para a comercialização, com pagamentos via PIX e entregas em locais combinados. As drogas, que incluíam a modalidade conhecida como ICE, eram distribuídas em Salvador, Vitória da Conquista, Santo Antônio de Jesus e Ilhéus, além de Aracaju, em Sergipe. Parte do tráfico interestadual envolvia fornecedores de São Paulo e do Paraguai, com a camuflagem dos entorpecentes em produtos de beleza. Durante a ação, foram apreendidos veículos de alto valor, como Audi e Jeep, além de uma pistola encontrada com um médico investigado.', 'https://api.proradiobr.com/imagens-publicas/operacao-iceberg-prende-11-suspeitos-e-apreende-veiculos-de-luxo-em-esquema-de.webp', '91925efe-8c0d-42a7-8e21-1d167b8f670b', '1e79060a-b850-4054-ae69-783db846d5fd', '2026-09-24 15:54:22.149276+00', 1007, true, 'Operação Iceberg: 11 presos e R$ 200 mi bloqueados no tráfico na Bahia', 'Polícia Civil deflagra operação contra grupo que vendia drogas para médicos e empresários na Bahia. Onze presos, veículos apreendidos e bloqueio patrimonial.')
ON CONFLICT (id) DO NOTHING;
